### ISSUE TITLE
Add type and status validators

### ISSUE THREAD

**Issue by BarracudaPff** [apmath-web/validation#8]
- Add TypeValidator for Application's [statuses](https://docs.google.com/document/d/1RiURQhXa6QD7rrq4720uTNWcksZWoBAFmj54RSLcgUg/edit#bookmark=id.j841mxhac3xx) 
- Add StatusValidator for Payment's [types](https://docs.google.com/document/d/1RiURQhXa6QD7rrq4720uTNWcksZWoBAFmj54RSLcgUg/edit#bookmark=id.llqnuauifkf)

**Comment by BarracudaPff** [comment]
@malinink 
Добавьте, пожалуйста, разрешение на push для Kotlin-team 
```bash
remote: Permission to apmath-web/validation.git denied to BarracudaPff.
fatal: unable to access 'https://github.com/apmath-web/validation.git/': The requested URL returned error: 403
```

**Comment by malinink** [comment]
Уже есть, называется Range

**Comment by malinink** [comment]
Тем не менее, права дал

**Comment by BarracudaPff** [comment]
Увидел https://github.com/apmath-web/validation/pull/7, спасибо
